# 실습 - 백터와 행렬

### 파이썬을 이용한 행렬 & 백터 처리

In [1]:
import numpy

a = numpy.array([0, 1, 2, 3])
print(a, end="\n")

b = numpy.arange(10).reshape(2, 5)
print(b, end="\n")

print(b.shape, end="\n")
print(b.ndim, end="\n")
print(b.size, end="\n")
print(b[(1, 2)], end="\n")
print(b[1, 2], end="\n")

[0 1 2 3]
[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)
2
10
7
7


In [6]:
import numpy

a = numpy.arange([1, 2, 3, 3, 2, 5]).reshape(2, 3)
b = numpy.arange([[-1, 3, 5], [1, 4, 2]])
print(a+b, end="\n")
print(a-b, end="\n")
print(a*b, end="\n")
print(a/b, end="\n")

c = numpy.arange([1, 2, 3, 4, 5]).reshape(3, 2)
print(c, end="\n")

print(numpy.dot(a, c), end="\n")
print(numpy.dot(b, c), end="\n")
print(numpy.dot(a, b), end="\n")

TypeError: unsupported operand type(s) for -: 'list' and 'int'